### ISSUE TITLE
Grading when create a new "Response-Attempt" Object

### ISSUE THREAD

**Issue by haotianzhu** [rw-moore/SciLO#6]
**Describe the solution you'd like**
Grading and saving result into response-attempt when creating response-attempt.
Student submit responses' answers, creating new response-attempts.  Response-attempts should not be modified when it is created.

**Comment by haotianzhu** [comment]
Only admin allows to modify attempts relative objects

**Comment by rw-moore** [comment]
Do we really need a completely new response-attempt for every single answer the student submits to every response in every question? I am worried that this will spam the database with vast numbers of entries. If a single course has 10 quizzes each with 10 questions with say and average of 2 responses per question and each student can make 10 attempts that's 2,000 DB entries per student per course. So for large courses we will be pushing 1 million DB entries for the quizzes per course which sounds like a lot!

Additionally, it seems unnecessary since we will only ever want to access all the responses attempts at once.

I'd suggest one of the following:
 - Have each response attempt store all the student entries as a pickled python list of strings (or something more efficient). This gives a factor 10 reduction (if 10 attempts/response).
 - Merge the question and response attempts so that one question attempt stores all entries for all responses in the question. This gives a factor 20 reduction (10 attempts/response, 2 responses/question).

**Comment by haotianzhu** [comment]
If we plan to use pickle to store json object, why would we not use postgre, the django support json field for postgre directly. And azure cloud supports postgre as well.
Postgre:  https://www.postgresql.org/
Django Json Field: https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/fields/#django.contrib.postgres.fields.JSONField

**Comment by haotianzhu** [comment]
Use postgre json field to store response-attempt
